---
language: python
services: docker

env:
  global:
    - ROLE_NAME: wikijs
  matrix:
    - MOLECULE_DISTRIB: debian10:latest

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - pip install molecule yamllint ansible-lint docker

before_script:
  - cd ../
  - mv ansible-$ROLE_NAME supertarto.$ROLE_NAME
  - cd supertarto.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
